name: TWITCH
on:
  schedule:
    # Runs every Mon
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme-with-twitch:
    name: Update this repo's README with latest video list
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "TWITCH" 
          feed_list: "https://twitchrss.appspot.com/vodonly/eaglepb2"
